'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Archive, ArrowLeft, ArrowRight, BookOpen, Check, Download, FileUp, Pencil, Plus, Search, Users, X } from 'lucide-react';
import { useApp } from './app-context';
import { LanguageTabs } from './workspace';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './ui/dialog';
import { SpeakerButton } from './learning';
import { parseVocabularyCsv, type ImportWord } from '@/lib/import';
import { LANGUAGES, type Deck, type Word } from '@/lib/types';

type Editor = { kind:'deck'; deck?:Deck } | { kind:'word'; word?:Word; deck:Deck } | { kind:'archive-deck'; deck:Deck } | { kind:'archive-word'; word:Word } | { kind:'import'; deck:Deck } | null;

export function DecksPage({ deckId }: { deckId?: string }) {
  const { data, language, run, busy, notify } = useApp();
  const [search, setSearch] = useState('');
  const [onlyMine, setOnlyMine] = useState(false);
  const [editor, setEditor] = useState<Editor>(null);
  const [limit, setLimit] = useState(30);
  const deck = data.decks.find(item => item.id === deckId);
  const termQuery = search.trim().toLocaleLowerCase('vi');
  const words = data.words.filter(word => word.deck_id === deckId && !word.archived && [word.term,word.pronunciation,word.meaning].some(value => value.toLocaleLowerCase('vi').includes(termQuery)));
  const decks = data.decks.filter(item => item.language === language && !item.archived && (!onlyMine || item.owner_id === data.profile.id) && `${item.name} ${item.description}`.toLocaleLowerCase('vi').includes(termQuery));
  const learned = new Set(data.progress.map(item => item.word_id));
  const editable = deck?.owner_id === data.profile.id;

  if (deckId && !deck) return <section className="empty-state panel"><BookOpen /><h1>Bộ từ không còn khả dụng</h1><p>Bộ từ có thể đã được lưu trữ hoặc không còn được chia sẻ với bạn.</p><Link href="/decks" className="button primary">Về thư viện</Link></section>;
  return <>
    {deck && <Link href="/decks" className="text-link back-link"><ArrowLeft size={17} /> Thư viện của bạn</Link>}
    <section className="page-heading"><div><p className="eyebrow">{deck ? LANGUAGES[deck.language].label.toUpperCase() : 'MỖI BỘ TỪ, MỘT CÁNH CỬA'}</p><h1>{deck?.name || 'Thư viện từ vựng'}</h1><p className="muted">{deck?.description || 'Chọn điều bạn muốn học. Cùng góp thêm những từ của riêng hai đứa.'}</p></div><div className="button-row">{deck ? editable && <><button className="button outline" onClick={() => setEditor({kind:'import',deck})}><FileUp size={17} /> Nhập CSV</button><button className="button primary" onClick={() => setEditor({kind:'word',deck})}><Plus size={18} /> Thêm từ</button></> : <button className="button primary" onClick={() => setEditor({kind:'deck'})}><Plus size={18} /> Tạo bộ từ</button>}</div></section>
    <div className="library-toolbar">{!deck && <LanguageTabs />}<label className="search-box"><Search size={18} /><input aria-label={deck ? 'Tìm từ vựng' : 'Tìm bộ từ'} value={search} onChange={event => {setSearch(event.target.value);setLimit(30);}} placeholder={deck ? 'Tìm từ, phiên âm hoặc nghĩa…' : 'Tìm chủ đề bạn muốn học…'} />{search && <button onClick={() => setSearch('')} aria-label="Xóa tìm kiếm"><X size={15} /></button>}</label>{!deck && <label className="checkbox-label"><input type="checkbox" checked={onlyMine} onChange={event => setOnlyMine(event.target.checked)} /> Của tôi</label>}</div>
    {deck ? <>
      <div className="deck-detail-meta"><span className="badge">{words.length} từ</span><span className="badge mint">{words.filter(word => learned.has(word.id)).length} đã học</span><span className="muted">{deck.owner_id ? editable ? 'Bộ từ của bạn · tự chia sẻ trong cặp' : 'Bộ từ của người cùng học' : 'Bộ từ có sẵn · Cơ bản'}</span>{editable && <div className="button-row"><button className="button ghost small" onClick={() => setEditor({kind:'deck',deck})}><Pencil size={14} /> Sửa bộ từ</button><button className="button ghost small" onClick={() => setEditor({kind:'archive-deck',deck})}><Archive size={14} /> Lưu trữ</button></div>}</div>
      {words.length ? <><div className="word-list panel">{words.slice(0,limit).map((word,index) => <article key={word.id} className="word-row"><span className="word-number">{String(index+1).padStart(2,'0')}</span><div className="word-main"><strong lang={word.language === 'zh' ? 'zh-CN' : 'en'}>{word.term}</strong><span>{word.pronunciation}</span></div><div className="word-definition"><strong>{word.meaning}</strong><p>{word.example_sentence}</p><span>{word.example_translation}</span></div><div className="word-actions">{learned.has(word.id) && <span className="learned-check" title="Đã học"><Check size={15} /></span>}<SpeakerButton term={word.term} language={word.language} />{editable && <><button className="icon-button" aria-label={`Sửa từ ${word.term}`} onClick={() => setEditor({kind:'word',word,deck})}><Pencil size={16} /></button><button className="icon-button" aria-label={`Lưu trữ từ ${word.term}`} onClick={() => setEditor({kind:'archive-word',word})}><Archive size={16} /></button></>}</div></article>)}</div>{limit < words.length && <button className="button outline load-more" onClick={() => setLimit(limit+30)}>Xem thêm {Math.min(30,words.length-limit)} từ</button>}</> : <div className="empty-state panel"><BookOpen /><h3>{search ? 'Chưa tìm thấy từ phù hợp' : 'Bộ từ đang chờ trang đầu tiên'}</h3><p>{search ? 'Thử tìm bằng từ hoặc nghĩa tiếng Việt khác nhé.' : 'Thêm từ thủ công hoặc nhập nhanh bằng file CSV.'}</p>{editable && !search && <button className="button primary" onClick={() => setEditor({kind:'word',deck})}><Plus size={17} /> Thêm từ đầu tiên</button>}</div>}
    </> : <div className="deck-grid">{decks.map((item,index) => {
      const deckWords = data.words.filter(word => word.deck_id === item.id && !word.archived);
      const count = deckWords.filter(word => learned.has(word.id)).length;
      return <Link href={`/decks/${item.id}`} className={`deck-card panel ${LANGUAGES[item.language].className}`} key={item.id}><div className="deck-card-top"><span className={`deck-icon tone-${index%4}`}><BookOpen size={23} /></span><span className="badge">{item.owner_id ? <><Users size={12} /> {item.owner_id === data.profile.id ? 'Của bạn' : 'Cùng chia sẻ'}</> : item.level}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="deck-card-preview" lang={language === 'zh' ? 'zh-CN' : 'en'}>{deckWords.slice(0,3).map(word => <span key={word.id}>{word.term}</span>)}</div><div className="deck-progress"><span>{count}/{deckWords.length} từ đã học</span><ArrowRight size={17} /></div><div className="progress-track"><div style={{width:`${deckWords.length ? count/deckWords.length*100 : 0}%`}} /></div></Link>;
    })}{decks.length === 0 && <div className="empty-state panel"><BookOpen /><h3>{search ? 'Chưa tìm thấy bộ từ phù hợp' : onlyMine ? 'Tạo bộ từ đầu tiên của bạn' : 'Chưa có bộ từ'}</h3><p>{search ? 'Thử một chủ đề khác nhé.' : 'Thêm những từ bạn gặp trong cuộc sống mỗi ngày.'}</p></div>}</div>}
    <Dialog open={!!editor} onOpenChange={open => { if (!open && !busy) setEditor(null); }}><DialogContent><EditorForm key={editor ? `${editor.kind}-${'word' in editor ? editor.word?.id : 'deck' in editor ? editor.deck?.id : ''}` : 'closed'} editor={editor} onClose={() => setEditor(null)} onSave={async (method,params,message) => { const ok = await run(method,params,message); if (ok) setEditor(null); return ok; }} notify={notify} /></DialogContent></Dialog>
  </>;
}

type Save = (method: Parameters<ReturnType<typeof useApp>['run']>[0], params: Record<string,unknown>, message: string) => Promise<boolean>;
function EditorForm({ editor, onClose, onSave, notify }: { editor:Editor; onClose:()=>void; onSave:Save; notify:(message:string,error?:boolean)=>void }) {
  const { language, busy } = useApp();
  const [parsed, setParsed] = useState<{words:ImportWord[];errors:string[];total:number} | null>(null);
  if (!editor) return null;
  if (editor.kind === 'import') return <><DialogTitle>Nhập từ từ file CSV</DialogTitle><DialogDescription>Chọn file UTF-8 theo mẫu. Kiểm tra trước khi thêm vào bộ “{editor.deck.name}”.</DialogDescription><a className="text-link" href="/import-template.csv" download><Download size={16} /> Tải file mẫu</a><label className="upload-zone"><FileUp size={30} /><strong>Chọn file CSV</strong><span>Tối đa 2 MB · 1.000 từ mỗi lần</span><input type="file" accept=".csv,text/csv" disabled={busy} onChange={async event => {const file = event.target.files?.[0];if (!file) return;if (file.size > 2*1024*1024) {notify('File lớn hơn 2 MB. Hãy chia nhỏ file.',true);return;}setParsed(parseVocabularyCsv(await file.text()));}} /></label>{parsed && <div className="import-preview"><p><strong>{parsed.words.length}</strong> từ hợp lệ / {parsed.total} dòng</p>{parsed.errors.length > 0 && <div className="error-message" role="alert">{parsed.errors.slice(0,10).map(error => <p key={error}>{error}</p>)}{parsed.errors.length>10 && <p>Và {parsed.errors.length-10} lỗi khác.</p>}</div>}<div className="import-preview-rows">{parsed.words.slice(0,8).map(word => <div key={word.term}><strong>{word.term}</strong><span>{word.meaning}</span></div>)}</div></div>}<div className="dialog-actions"><button className="button outline" disabled={busy} onClick={onClose}>Đóng</button><button className="button primary" disabled={busy || !parsed?.words.length || !!parsed.errors.length} onClick={() => onSave('import_words',{p_deck_id:editor.deck.id,p_words:parsed!.words},'Đã nhập bộ từ. Những từ trùng được bỏ qua.')}>{busy ? 'Đang nhập…' : `Nhập ${parsed?.words.length || 0} từ`}</button></div></>;
  if (editor.kind === 'archive-deck' || editor.kind === 'archive-word') return <><DialogTitle>Lưu trữ {editor.kind === 'archive-deck' ? 'bộ từ' : 'từ vựng'}?</DialogTitle><DialogDescription>Mục này sẽ dừng xuất hiện trong thư viện và bài học mới. Lịch sử học được giữ lại cho cả hai người.</DialogDescription><div className="dialog-actions"><button className="button outline" disabled={busy} onClick={onClose}>Để sau</button><button className="button danger" disabled={busy} onClick={() => editor.kind === 'archive-deck' ? onSave('archive_deck',{p_deck_id:editor.deck.id},'Đã lưu trữ bộ từ.') : onSave('archive_word',{p_word_id:editor.word.id},'Đã lưu trữ từ vựng.')}>Lưu trữ</button></div></>;
  if (editor.kind === 'deck') return <><DialogTitle>{editor.deck ? 'Chỉnh sửa bộ từ' : 'Một bộ từ mới'}</DialogTitle><DialogDescription>Những từ của bạn sẽ tự chia sẻ với người cùng cặp.</DialogDescription><form className="form-stack" onSubmit={async event => {event.preventDefault();const form = new FormData(event.currentTarget);await onSave('save_deck',{p_id:editor.deck?.id || null,p_language:form.get('language'),p_name:form.get('name'),p_description:form.get('description')},'Đã lưu bộ từ.');}}><label className="field">Tên bộ từ<input name="name" defaultValue={editor.deck?.name} required maxLength={100} placeholder="Ví dụ: Những từ trong phim chúng mình xem" /></label><label className="field">Ngôn ngữ<select name="language" defaultValue={editor.deck?.language || language} disabled={!!editor.deck}><option value="zh">Tiếng Trung</option><option value="en">Tiếng Anh</option></select>{editor.deck && <input name="language" type="hidden" value={editor.deck.language} />}</label><label className="field">Mô tả<textarea name="description" defaultValue={editor.deck?.description} maxLength={500} placeholder="Một vài dòng về bộ từ này…" rows={3} /></label><div className="dialog-actions"><button type="button" className="button outline" disabled={busy} onClick={onClose}>Để sau</button><button className="button primary" disabled={busy}>Lưu bộ từ</button></div></form></>;
  const word = editor.word;
  return <><DialogTitle>{word ? 'Chỉnh sửa từ vựng' : 'Thêm một từ mới'}</DialogTitle><DialogDescription>Thêm phiên âm và ví dụ để bài học dễ nhớ hơn.</DialogDescription><form className="form-stack" onSubmit={async event => {event.preventDefault();const form = new FormData(event.currentTarget);await onSave('save_word',{p_id:word?.id || null,p_deck_id:editor.deck.id,p_word:{term:form.get('term'),pronunciation:form.get('pronunciation'),meaning:form.get('meaning'),example_sentence:form.get('example_sentence'),example_translation:form.get('example_translation'),accepted_answers:String(form.get('accepted_answers') || '').split('|').map(value=>value.trim()).filter(Boolean)}},'Đã lưu từ vựng.');}}><div className="form-columns"><label className="field">Từ vựng<input name="term" defaultValue={word?.term} required maxLength={100} /></label><label className="field">{editor.deck.language === 'zh' ? 'Pinyin có dấu' : 'Phiên âm'}<input name="pronunciation" defaultValue={word?.pronunciation} required maxLength={200} /></label></div><label className="field">Nghĩa tiếng Việt<input name="meaning" defaultValue={word?.meaning} required maxLength={500} /></label><label className="field">Câu ví dụ có chứa từ<input name="example_sentence" defaultValue={word?.example_sentence} required maxLength={1000} /></label><label className="field">Dịch câu ví dụ<input name="example_translation" defaultValue={word?.example_translation} required maxLength={1000} /></label><label className="field">Đáp án khác được chấp nhận <span className="optional">(tùy chọn, ngăn bằng |)</span><input name="accepted_answers" defaultValue={word?.accepted_answers.join(' | ')} maxLength={1000} /></label><div className="dialog-actions"><button type="button" className="button outline" disabled={busy} onClick={onClose}>Để sau</button><button className="button primary" disabled={busy}>Lưu từ vựng</button></div></form></>;
}
